//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lark.StringGet {
    using System;
    
    
    public partial class MainForm {
        
        public static string GetBuildTime() {
            return "2008-06-12 17:27:24";
        }
    }
}
